CC = g++
CFLAGS = -std=c++11 -ggdb3

removeDup:removeDup.cpp
	$(CC) $(CFLAGS) -o removeDup removeDup.cpp
kth:ListNode.h kthLast.cpp
	$(CC) $(CFLAGS) -o kth ListNode.h kthLast.cpp
clean:
	rm -f *.cpp~ *.h~ *~
