CC = g++
CFLAGS = -std=c++11 -ggdb3

removeDup:removeDup.cpp
	$(CC) $(CFLAGS) -o removeDup removeDup.cpp
kth:ListNode.h kthLast.cpp
	$(CC) $(CFLAGS) -o kth ListNode.h kthLast.cpp
partition:partition.cpp
	$(CC) $(CFLAGS) -o partition partition.cpp
loop:detectLoop.cpp
	$(CC) $(CFLAGS) -o loop detectLoop.cpp
clean:
	rm -f *.cpp~ *.h~ *~
