CC = g++
CFLAGS = -std=c++11 -ggdb3

Permutation: isPermutation.cpp
	$(CC) $(CFLAGS) -o Permutation isPermutation.cpp
url:URLify.cpp
	$(CC) $(CFLAGS) -o url URLify.cpp
palindrome: isPalinPermute.cpp
	$(CC) $(CFLAGS) -o palindrome isPalinPermute.cpp
rotateMatrix: rotateMatrix.cpp
	$(CC) $(CFLAGS) -o rotateMatrix rotateMatrix.cpp
clean:
	rm -f *.cpp~ *~
